### ISSUE TITLE
error parsing markup: Attribute 'class' is not allowed on the <a> tag

### ISSUE THREAD

**Issue by martensitingale** [bleakgrey/tootle#10]
White running tootle I see a few warnings like the following printed in the terminal:

(com.github.bleakgrey.tootle:11030): Gtk-WARNING **: 10:07:57.909: Failed to set text '@<a href="https://chaos.social/users/saxnot" class="h-card u-url p-nickname mention"  >saxnot</a> Bitte <a href="https://friend.d5e.org/profile/dirk"   >https://friend.d5e.org/profile/dirk</a> folgen, der Account lebt nicht mehr lange.' from markup due to error parsing markup: Attribute 'class' is not allowed on the <a> tag on line 1 char 96

It seems self-explanatory enough.

**Comment by bleakgrey** [comment]
Yup, seems like it needs more Regex'ing
