### ISSUE TITLE
Watchlist has a different window type than settings and new toot

### ISSUE THREAD

**Issue by tastytea** [bleakgrey/tootle#101]
The watchlist dialog looks different than the others. `xprop` reports `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL` for the watchlist, while settings and new toot are set to `_NET_WM_WINDOW_TYPE_DIALOG`.

![screenshot_tootle_dialogs](https://user-images.githubusercontent.com/3681516/47721694-9a57c700-dc48-11e8-9a7d-939e60ee98d3.png)

**Comment by bleakgrey** [comment]
Ah, so that leads to design inconsistency. I'll tweak that.

**Comment by bleakgrey** [comment]
Please test the master branch to see if it's displaying as a modal dialog now

**Comment by tastytea** [comment]
The window type is `_NET_WM_WINDOW_TYPE_DIALOG` now, but it still looks as before. I found out that the decorations bit in `_MOTIF_WM_HINTS` is unset, as opposed to the other dialogs.

For settings and new toot, `_MOTIF_WM_HINTS` is set to `0x1, 0x21, 0x0, 0x0, 0x0`, while for the watchlist it is set to `0x2, 0x0, 0x0, 0x0, 0x0`.

Here is some more info on `_MOTIF_WM_HINTS`: http://mathematicalcoffee.blogspot.com/2012/05/automatically-undecorate-maximised.html

**Comment by bleakgrey** [comment]
What OS are you using?

**Comment by tastytea** [comment]
Gentoo, with i3-4.15 as window manager.

**Comment by tastytea** [comment]
The window looks still different, `_MOTIF_WM_HINTS` is still different.

**Comment by bleakgrey** [comment]
I literally can't do anything else without breaking it for Juno
