### ISSUE TITLE
Crash right after opening on Arch

### ISSUE THREAD

**Issue by ekianjo** [bleakgrey/tootle#107]
It used to work fine until today.

Here are the messages from the Terminal:

Application.vala:155: Tootle version: 0.2.0
Application.vala:157: Kernel version: 4.19.1-arch1-1-ARCH
Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
(com.github.bleakgrey.tootle:4942): Gtk-WARNING **: 20:14:14.174: gtk_window_set_titlebar() called on a realized window
[INFO] Watchlist.vala:23: Reloading
[INFO] Watchlist.vala:34: Watching for 0 users and 0 hashtags
[ERROR] [GLib-GIO] Settings schema 'io.elementary.desktop.wingpanel.datetime' is not installed
Trace/breakpoint trap (core dumped)

**Comment by goupildb** [comment]
On 64-bit Debian Sid, libgranite has been updated on November 09, 2018.
Tootle worked in this period, then stopped working from November 14, 2018 to November 16, 2018, and yesterday, November 19, 2018 he crashed again on the same messages, without Granite being updated. Strange.

gir1.2-granite-1.0 (5.1.0-2) to 5.2.1-1
libgranite-common (5.1.0-2) to 5.2.1-1
libgranite-dev (5.1.0-2) to 5.2.1-1
libgranite5 (5.1.0-2) to 5.2.1-1

I downgrade granite to 5.1.0-+2 and then Tootle work again.

**Comment by FedericoCeratto** [comment]
Temporary workaround for Debian (and possibly Ubuntu) users: download the package for your architecture from https://snapshot.debian.org/package/granite/5.1.0-2/\#libgranite5_5.1.0-2 and install it with `sudo dpkg -i <filename>`

**Comment by bleakgrey** [comment]
@decathorpe Any chance this is going to be ever fixed? I see that you've closed your PR and the upstream still doesn't have this changed.

**Comment by decathorpe** [comment]
@bleakgrey I don't know. The branch for my PR had diverged from upstream significantly, which is why I closed it for now. However, I've rebased my patch and fixed this issue for the official fedora packages (with a - hopefully temporary - downstream patch), but I've not been able to work with the elementary developers to find an acceptable solution for upstream inclusion. I think that I proposed a workable solution until it can be solved in a better way, but the perfect seems to be the enemy of the good in this case.

**Comment by TanyaEleventhGoddess** [comment]
Affected by this bug too, I hope it will be fixed soon.

**Comment by decathorpe** [comment]
FYI, the latest release of granite (5.2.4) reverts the controversial change.

**Comment by TanyaEleventhGoddess** [comment]
Are you sure? It seems the latest version is 1.1.5
https://graphite.readthedocs.io/en/latest/install.html

**Comment by decathorpe** [comment]
> Are you sure? It seems the latest version is 1.1.5 https://graphite.readthedocs.io/en/latest/install.html

@TanyaEleventhGoddess You seem to be confusing the granite and graphite libraries.

**Comment by TanyaEleventhGoddess** [comment]
The packages libgraphite2-dev on debian are still on versions 1.*, even
in sid
I find unlikely that graphite libraries are so far away even from sid
repo, but I'll avoid stating this as certain

**Comment by ldutra** [comment]
> The packages libgraphite2-dev on debian are still on versions 1.*, even in sid I find unlikely that graphite libraries are so far away even from sid repo, but I'll avoid stating this as certain

This is about Granite, not Graphite.
