### ISSUE TITLE
Build without installing in /usr

### ISSUE THREAD

**Issue by stevenroose** [bleakgrey/tootle#114]
These are the "install instructions":
```
$ meson build --prefix=/usr
$ cd build
$ sudo ninja install
$ com.github.bleakgrey.tootle
```
I tried the following thing to just build Tootle without installing it in `/usr`:
```
$ mkdir install
$ meson build --prefix=/home/steven/code/tootle/install
$ cd build
$ ninja install
$ ./com.github.bleakgrey.tootle
[INFO 21:02:22.973187] Application.vala:155: Tootle version: 0.2.0
[INFO 21:02:22.973210] Application.vala:157: Kernel version: 4.19.4-arch1-1-ARCH
[ERROR 21:02:22.975586] [GLib-GIO] Settings schema 'com.github.bleakgrey.tootle' is not installed
[1]    5433 trace trap (core dumped)  ./com.github.bleakgrey.tootle
```

**Comment by bitkeks** [comment]
It works with some additional variables: `DESTDIR` and `GSETTINGS_SCHEMA_DIR` ([source](https://stackoverflow.com/questions/37916185/how-to-fix-error-glib-gio-error-no-gsettings-schemas-are-installed-on-the-sy)).

```bash
meson build
ninja -C build
cd build
DESTDIR="install" ninja install
glib-compile-schemas install/usr/local/share/glib-2.0/schemas/
GSETTINGS_SCHEMA_DIR=install/usr/local/share/glib-2.0/schemas/ install/usr/local/bin/com.github.bleakgrey.tootle
```

Yet, the interface has encoding errors and does not show instance emojis.

**Comment by o-jasper** [comment]
Looks like it needs more schemas? Get `[ERROR 22:05:17.996583] [GLib-GIO] Settings schema 'io.elementary.desktop.wingpanel.datetime' is not installed` i dont see it in `/usr/share/glib-2.0/schemas/` though, don't know which packages has it? (aside: also get bunch of errors about an ampersand left in a toot)
