### ISSUE TITLE
Tootle does not appear in french

### ISSUE THREAD

**Issue by anto1ne** [bleakgrey/tootle#117]
Hi, 

I came here because I saw that Tootle appear in english on my computer (xubuntu 18.04, I am french).

I saw that the translation has already been complete (https://github.com/bleakgrey/tootle/tree/master/po). 
Is it a bug or am I running a too old version ? (https://github.com/bleakgrey/tootle/issues/116)

**Comment by bleakgrey** [comment]
Did you compile it yourself or install Flatpak version?
You can check the version you're running with typing `com.github.bleakgrey.tootle` in the terminal

**Comment by toitoinebzh** [comment]
information about my version can be found here
https://github.com/bleakgrey/tootle/issues/116

Tootle version: 0.2.0
tootle 0+git.2362257

I installed it by snap with the ubuntu software center
