### ISSUE TITLE
"New toot window" can't erase text correctly

### ISSUE THREAD

**Issue by sputnikmoment** [bleakgrey/tootle#119]
Fedora 29 x86_64, default Gnome DE, classic mode.
Flatpak install, fresh.
Terminal:
`bash-4.4$ flatpak run com.github.bleakgrey.tootle
Gtk-Message: 17:49:45.985: Failed to load module "pk-gtk-module"
Gtk-Message: 17:49:45.986: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:49:45.986: Failed to load module "pk-gtk-module"
Gtk-Message: 17:49:45.986: Failed to load module "canberra-gtk-module"
[INFO 17:49:45.987850] Application.vala:155: Tootle version: 0.2.0
[INFO 17:49:45.988097] Application.vala:157: Kernel version: 4.19.8-300.fc29.x86_64
[INFO 17:49:46.156275] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 17:49:46.210803] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 17:49:46.220378] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 17:49:46.224463] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(com.github.bleakgrey.tootle:2): Gtk-WARNING **: 17:49:46.414: gtk_window_set_titlebar() called on a realized window
[INFO 17:49:47.003922] Watchlist.vala:23: Reloading
[INFO 17:49:47.004778] Watchlist.vala:34: Watching for 0 users and 0 hashtags
[FATAL 17:49:54.646971] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[INFO 17:49:57.285473] Notificator.vala:57: Closing: /api/v1/streaming/?stream=user
[INFO 17:49:57.288988] Notificator.vala:57: Closing: /api/v1/streaming/?stream=public:local
[INFO 17:49:57.290414] Notificator.vala:57: Closing: /api/v1/streaming/?stream=public
bash-4.4$ 
`
Bug description: 
Open new message window and start write a message. Every letter separates with vertical lines. If I start to erase any letter with backspace or delete - old letters image will not vanish visually. But tecnically will. I can push edited message in "blind mode".

**Comment by bleakgrey** [comment]
So the character counter is working as expected and this bug can be treated as a purely graphical glitch?

**Comment by bleakgrey** [comment]
I think I can pinpoint the source of this problem, but I can't reproduce it. Can you compile Tootle from source with some changes?

The problem must be in the file `data\main.css`, lines 20-22. Please remove those lines and compile Tootle to see if it worked.

**Comment by sputnikmoment** [comment]
unfortunately, I can't
I wanted to, but Fedora 29 do not have libgee08 library, only 06 and 20...
So there is an error in compile prosses:
bash-4.4$ meson build --prefix=/usr
The Meson build system
Version: 0.49.0
Source dir: /home/alex/Загрузки/tootle-master
Build dir: /home/alex/Загрузки/tootle-master/build
Build type: native build
Project name: com.github.bleakgrey.tootle
Project version: undefined
Native C compiler: ccache cc (gcc 8.2.1 "cc (GCC) 8.2.1 20181105 (Red Hat 8.2.1-5)")
Native Vala compiler: valac (valac 0.42.3)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.5.3)
Dependency gtk+-3.0 found: YES 3.24.1
Dependency glib-2.0 found: YES 2.58.1
Found CMake: /usr/bin/cmake (3.12.1)
Dependency gee-0.8 found: NO (tried pkgconfig and cmake)

meson.build:18:0: ERROR:  Dependency "gee-0.8" not found, tried pkgconfig and cmake

A full log can be found at /home/alex/Загрузки/tootle-master/build/meson-logs/meson-log.txt
bash-4.4$

**Comment by sputnikmoment** [comment]
> I think I can pinpoint the source of this problem, but I can't reproduce it. Can you compile Tootle from source with some changes?
> 
> The problem must be in the file `data\main.css`, lines 20-22. Please remove those lines and compile Tootle to see if it worked.

https://github.com/bleakgrey/tootle/tree/master/data

ah and there are NO data\main.css file in my sourses. Is that OK?

**Comment by bleakgrey** [comment]
Sorry, I meant the `app.css` one. I think you can try different libgee version too, it shouldn't break things too much.
