### ISSUE TITLE
Key Shortcuts

### ISSUE THREAD

**Issue by bleakgrey** [bleakgrey/tootle#12]
Ctrl + T = New toot
Alt + Backspace = Go back
Mouse Back = Go back
Alt + 1/2/3/4 = Switch timelines
F5; Ctrl + R = refresh

**Comment by martensitingale** [comment]
Additional keys to support are ctrl+enter for sending in the compose window, F5 and ctrl+R for refreshing, and backspace and alt-left for "back".

It would be great if when someone implements hotkeys they make sure to use the GtkAccelMap infrastructure to support customization: https://developer.gnome.org/gtk3/stable/gtk3-Accelerator-Maps.html

**Comment by bleakgrey** [comment]
Idea by @cassidyjames: using mouse's back button to jump back to the previous view.

The relevant bit from Switchboard:
https://github.com/elementary/switchboard/blob/601ced347ddcec960d9c9d5dd431349e92a6e528/src/Switchboard.vala#L346-L353

**Comment by cassidyjames** [comment]
I'd recommend against backspace to go back, as apps are moving away from that convention. If someone starts typing thinking they're in an entry, it's too easy for them to jump around the app and get confused.

Files, Chrome, Firefox, etc. have all dropped this. The convention seems to be <kbd>Alt</kbd>+<kbd>←</kbd>

**Comment by FedericoCeratto** [comment]
Configurable keys would be nice!

**Comment by bleakgrey** [comment]
@cassidyjames Cool, I'll look into it. Any approximate release dates for the updated Granite?

**Comment by cassidyjames** [comment]
@bleakgrey I'm not sure since it's not even merged yet. But it's a simple enough thing to do manually in the meantime. It's just a standard tooltip with some specific markup.
