### ISSUE TITLE
Characters don't appear correctly in profile text

### ISSUE THREAD

**Issue by klreeher** [bleakgrey/tootle#120]
I set my profile blurb to include the phrase "don't care, i'm a bear" on the mastodon.social instance's web interface.
When I checked my profile on tootle, however, the characters appeared as `don&apos;t care, i&apos;m a bear`. 

Updating my profile on the web interface with a few of the [blns](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.json), I found this to be fairly consistent
`eval(\"puts 'hello world'\")` > `eval(\&quot;puts &apos;hello world&apos;\&quot;)` etc.

My machine - Elementary 5.0 Juno, English language default. Tootle was installed from the AppCenter, v 0.2.0.

**Comment by bleakgrey** [comment]
![Screenshot from 2019-03-09 13-03-15](https://user-images.githubusercontent.com/20158357/54070025-fc66af80-426c-11e9-8250-2e2a28983a09.png)

Hopefully this will never screw up the labels again
