### ISSUE TITLE
Unqualified @user mentions from other instances are not resolved properly

### ISSUE THREAD

**Issue by 17dec** [bleakgrey/tootle#122]
E.g. when someone on mastodon.social toots `@user is awesome` (`@user` without the domain) and you are reading the toot from mastodon.technology, the `@user` is resolved as if it refers to `@user@mastodon.techonology`, resulting in a "User not found" error, It should instead refer to the instance where the toot originated from (i.e. `@user@mastodon.social`).

**Comment by bleakgrey** [comment]
Mentions are automatically resolved and turned into links by Mastodon, Tootle only displays them. I'm not sure I want to write custom logic to circumvent this behavior as it seems a bit out of the scope.

Please correct me if I'm wrong but I'm pretty sure that all clients are prone to this behavior.

**Comment by 17dec** [comment]
Hmm, I wasn't aware that Mastodon was responsible for resolving the links. Oddly enough I don't have this problem with the Mastodon web UI or with Subway Tooter.

I agree though that if it's Mastodon doing the resolving, then this isn't a problem that Tootle ought to solve.

**Comment by bleakgrey** [comment]
Closing this for now, might reopen later
