### ISSUE TITLE
Proposal: UX improvements

### ISSUE THREAD

**Issue by cleac** [bleakgrey/tootle#128]
Thanks very much for creating this application, I totally love it and would like to help making it even better and more awesome to users. So I've made a list of small proposals on how  user experience of an application could be improved very much. Those are proposals to think and discuss at first place :wink: 

So, here it goes:

1. Add proper support for "Home", "End", "PageUp", "PageDown" shortcuts that will allow to navigate faster through opened tabs

2. Add possibility to jump to top if already opened tab by clicking on it or pressing corresponding keystroke that should open it. Here is an example use-case: `You scrolled down through "Home timeline" at some place` -> `You click on "Home" logo on window decoration` -> `Viewport jumps to the top and (probably) new toots are fetched`

3. When viewing a thread, add possibility to hide/display all CW toots in thread currently displayed with one click in toolbar.

4. Add possibility to resize text, because sometimes text feels to small compared to any other application that displays text in Gnome environment. Probably this one is related to #112, but it would make application feel _way_ more close to user

----

Some of these I could implement myself as well, but there is still not much time I have to do it, so I would like discuss some of them at first place and then after maintainers' approval implement :smile:

**Comment by bleakgrey** [comment]
I like every single one of these. Please create an issue for each list item and I'll take care of them one by one :)
