### ISSUE TITLE
No max width limit on compose window

### ISSUE THREAD

**Issue by drequivalent** [bleakgrey/tootle#130]
The compose dialog gets stretched as I type more characters.

![screenshot from 2019-02-12 04-10-07](https://user-images.githubusercontent.com/1463277/52604520-3fa34d80-2e7c-11e9-8bd5-5a295a1d2a7d.png)

Installed version: 0.2.0

**Comment by bleakgrey** [comment]
Referenced wrong issue, this one is still broken
