### ISSUE TITLE
Tootle doesn't update after network downtime

### ISSUE THREAD

**Issue by drequivalent** [bleakgrey/tootle#131]
After a long network downtime (like, the computer being suspended), Tootle stays open with exactly the same state as when the downtime started, with no updates afterwards.

The user has to restart Tootle to get new messages.

Probable solution is to poll the websocket for connection status and reconnect if it goes down.

**Comment by bleakgrey** [comment]
The funny thing is that it should be able to reconnect. I guess I broke that behavior again.

**Comment by bleakgrey** [comment]
67c4a1f should do the thing now
