### ISSUE TITLE
Confusing behavior with "Always receive notifications"

### ISSUE THREAD

**Issue by FedericoCeratto** [bleakgrey/tootle#133]
When "Always receive notifications" is set under Settings, tootle runs in background without creating a tray icon. There's no way tell that it is running (other than using pgrep) or to open it again ("pop it up" so to speak) without starting the application again.

**Comment by bleakgrey** [comment]
This is the intended behavior for elementary OS as most of the apps there behave like this as well.

Besides, third-party indicators are being deprecated and no longer will be visible. While I don't agree with this decision, I can see why it was made. The current behavior seems good enough for me at this point.

I agree that "Always receive notifications" sounds a bit inexplicit, so I'll just rephrase that with something like "Receive notifications in background".
