### ISSUE TITLE
Add possibility to display all thread's content warnings at once

### ISSUE THREAD

**Issue by cleac** [bleakgrey/tootle#137]
This is a proposal, detached from #128 by request of @bleakgrey.

## Proposal

Add some kind of button at top bar that toggles all the content warning state at once to simplify user. The idea from official mastodon web application.

#### Closed content warnings
![closed content warnings picture](https://user-images.githubusercontent.com/8603674/54149317-8154f300-443e-11e9-997d-8d14982bd0c6.png)

#### Opened content warnings
![opened content warnings picture](https://user-images.githubusercontent.com/8603674/54149397-b3665500-443e-11e9-9de0-a8ba8dd750bb.png)

**Comment by bleakgrey** [comment]
I wonder if this needs a hotkey for the expanded status view too...

**Comment by cleac** [comment]
Yeah, that would be great too :smile:

**Comment by bleakgrey** [comment]
Assigned hotkey: `Ctrl + S`
