### ISSUE TITLE
Add some possibility to resize text 

### ISSUE THREAD

**Issue by cleac** [bleakgrey/tootle#138]
This is a proposal, detached from #128 by request of @bleakgrey.

## Proposal

Add possibility to resize text, because sometimes text feels to small compared to any other application that displays text in Gnome environment. Probably this one is related to #112, but it would make application feel way more close to user.

General idea is to put this thing inside settings and allow to regulate this parameter as user wants.

**Comment by bleakgrey** [comment]
Dupe of #86
