### ISSUE TITLE
Segfault when trying to follow a person on master build

### ISSUE THREAD

**Issue by cleac** [bleakgrey/tootle#145]
**Reproduced only on build from _master_ branch**

**Issue**:

When I try following any account using button "Follow" on Accounts page, I get segfault. Reproducing an issue with debugger attached showed that the issue is at this place:
```
Thread 1 "com.github.blea" received signal SIGSEGV, Segmentation fault.
0x00005555555a4769 in __lambda71_ (self=0x555556fe8870)
     at src/Views/Profile.vala:135
135	        button_follow.clicked.connect (() => account.set_following (!account.rs.following));
```

I can investigate this further if you mind :wink:

**Comment by bleakgrey** [comment]
No longer relevant for the "refactor" branch.
