### ISSUE TITLE
Modifications requests (first one is important)

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [bleakgrey/tootle#156]
*Should be prioritized in my opinion:*
Allowing mentions of people on other instances by using @user@instance

Others in importance order:
Emoji support (currently they're displayed as :emoji:)
Possibility of setting default behaviour for posts (public timelines, followers, mentioned)
Support for adding images in posts by drag ad drop

**Comment by bleakgrey** [comment]
Please post each suggestion as a separate issue for simplicity's sake.
