### ISSUE TITLE
Icon redesign

### ISSUE THREAD

**Issue by bleakgrey** [bleakgrey/tootle#162]
The application icon needs a redesign to comply with the GNOME guidelines (https://developer.gnome.org/hig/stable/icon-design.html.en). If you wish to contribute to this project, please let me know.

**Comment by bertob** [comment]
Hey, I'd be happy to help with that :)

What do you have in mind in terms of metaphor? Keep the current trumpet? Something else specific?

**Comment by bleakgrey** [comment]
Hey @bertob, thank you for your assistance! Please [email me](mailto:bleakgrey@gmail.com) and we'll discuss it further.

**Comment by bleakgrey** [comment]
Thanks once again! Finally merged it into master ❤️
