### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by benwaffle** [bleakgrey/tootle#163]
```
../src/Views/Abstract.vala:24.5-24.19: error: Creation method of abstract class cannot be public.
    public Abstract () {
    ^^^^^^^^^^^^^^^
```

on Vala 0.46.3

**Comment by rodneyrod** [comment]
Getting this in Manjaro AUR as well.

**Comment by fauno** [comment]
I made this patch (no idea about Vala though) but it ended up failing, I'm attaching build.log

```diff
--- src/Views/Abstract.vala.orig	2019-10-12 13:52:14.179913441 -0300
+++ src/Views/Abstract.vala	2019-10-12 14:23:13.926611089 -0300
@@ -21,7 +21,7 @@
         });
     }
 
-    public Abstract () {
+    Abstract () {
         show_all ();
     }
 
```

[tootle-git-0.2+r30+gd8fc951-1-x86_64-build.txt](https://github.com/bleakgrey/tootle/files/3721068/tootle-git-0.2%2Br30%2Bgd8fc951-1-x86_64-build.txt)

**Comment by benwaffle** [comment]
@fauno try `protected`

**Comment by bleakgrey** [comment]
Fixed in the `refactor` branch.
