### ISSUE TITLE
Doesn't run on Elementary OS

### ISSUE THREAD

**Issue by Xvatten** [bleakgrey/tootle#170]
$ com.github.bleakgrey.tootle 
[INFO 22:06:02.770424] Application.vala:156: Tootle version: 0.2.0
[INFO 22:06:02.770449] Application.vala:158: Kernel version: 5.3.0-40-generic
[INFO 22:06:02.797972] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 22:06:02.799721] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 22:06:02.802095] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 22:06:02.803033] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public
[INFO 22:06:03.166208] Watchlist.vala:23: Reloading
[INFO 22:06:03.166245] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:/build/com.github.bleakgrey.tootle-0.2.0/src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Aborted

**Comment by davidak** [comment]
We have the same problem on NixOS (https://github.com/NixOS/nixpkgs/issues/63089). So it's probably not related to the OS.

The developer works on a refactored version. (see activity here https://github.com/bleakgrey/tootle/commits/refactor)
So the best option is to wait for that.

If you care about the project, consider donating to the developer: https://liberapay.com/bleakgrey/donate
