### ISSUE TITLE
Tootle Crashes on Startup **Bug Report**

### ISSUE THREAD

**Issue by securerootd** [bleakgrey/tootle#172]
**What should happen:**
I should be able to use tootle

**What happened instead:**
Window opens and closes before even loading the feed. Same behavior every-time.

**How to reproduce:**
1. Open tootle
2. It crashes

**Build context:**
 - Distro: (X)ubuntu 20.04 LTS
 - Version: 0.2.0-2ubuntu1
 - Build type: Ubuntu Official Channel (apt)

**Logs:**
tootle
[INFO 20:56:12.382030] Application.vala:156: Tootle version: 0.2.0
[INFO 20:56:12.382076] Application.vala:158: Kernel version: 5.4.0-25-lowlatency
[INFO 20:56:12.456352] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 20:56:12.458930] Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
[INFO 20:56:12.462606] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
[INFO 20:56:12.464110] Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(tootle:8406): Gtk-WARNING **: 20:56:12.567: gtk_window_set_titlebar() called on a realized window
[INFO 20:56:13.919248] Watchlist.vala:23: Reloading
[INFO 20:56:13.919328] Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:../../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
Bail out! ERROR:../../src/API/NotificationType.vala:43:tootle_notification_type_from_string: code should not be reached
[1]    8406 abort (core dumped)  tootle

**Additional info:**
Not known

**Comment by bleakgrey** [comment]
...Ubuntu 20.04 has Tootle in its official repos? Uh oh. I should probably fix this.

**Comment by jmbmkn** [comment]
I'm having the same issue on elementary 5.1.4, anything we can do to troubleshoot?

**Comment by kolgza** [comment]
Same issue on Pop!_OS 20.04
<pre><font color="#4E9A06"><b>colin@colin-pc</b></font>:<font color="#3465A4"><b>~</b></font>$ flatpak run com.github.bleakgrey.tootle 
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">21:25:56.886</font>: Failed to load module &quot;appmenu-gtk-module&quot;
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">21:25:57.973</font>: Failed to load module &quot;canberra-gtk-module&quot;
Gtk-<font color="#4E9A06"><b>Message</b></font>: <font color="#3465A4">21:25:57.973</font>: Failed to load module &quot;canberra-gtk-module&quot;
<font color="#48B9C7">[INFO 21:25:57.974168]</font> Application.vala:155: Tootle version: 0.2.0
<font color="#48B9C7">[INFO 21:25:57.974202]</font> Application.vala:157: Kernel version: 5.4.0-7629-generic
<font color="#48B9C7">[INFO 21:25:58.305453]</font> Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
<font color="#48B9C7">[INFO 21:25:58.624704]</font> Notificator.vala:40: Starting: /api/v1/streaming/?stream=user
<font color="#48B9C7">[INFO 21:25:58.663502]</font> Notificator.vala:40: Starting: /api/v1/streaming/?stream=public:local
<font color="#48B9C7">[INFO 21:25:58.665233]</font> Notificator.vala:40: Starting: /api/v1/streaming/?stream=public

(com.github.bleakgrey.tootle:2): Gtk-<font color="#C4A000"><b>WARNING</b></font> **: <font color="#3465A4">21:26:03.234</font>: gtk_window_set_titlebar() called on a realized window
<font color="#48B9C7">[INFO 21:26:04.404878]</font> Watchlist.vala:23: Reloading
<font color="#48B9C7">[INFO 21:26:04.404956]</font> Watchlist.vala:34: Watching for 0 users and 0 hashtags
**
ERROR:com.github.bleakgrey.tootle@exe/src/API/NotificationType.c:215:tootle_notification_type_from_string: code should not be reached
<font color="#4E9A06"><b>colin@colin-pc</b></font>:<font color="#3465A4"><b>~</b></font>$ 
</pre>

**Comment by despens** [comment]
Using version 0.2.0 from flathub, which still exposes the crash-on-launch behavior.

**Comment by bleakgrey** [comment]
Tootle 1.0 is still WIP and will be published once it's ready.
