### ISSUE TITLE
Not sure if I'm supposed to post this here, but I can't find a package for libhandy-1.0-dev anywhere.

### ISSUE THREAD

**Issue by Scupake** [bleakgrey/tootle#177]
that's all

**Comment by bleakgrey** [comment]
Hey!

I probably should make it clear in the project's description or somewhere else.

You don't actually need it installed as Tootle will download, compile and install it automatically if it's not present in the system.

**Comment by bleakgrey** [comment]
Sooo I suppose I'll close this then
