### ISSUE TITLE
Phones needs smaller width

### ISSUE THREAD

**Issue by Alexmitter** [bleakgrey/tootle#179]
Hello

There is a issue with the minimal width of the MainWindow preventing the app from working right on mobile devices. Currently those devices all have 720p displays and range from a scaling factor of 1.5 to 2. So a minimum MainWindow width of 360px is needed.

![tootle1](https://user-images.githubusercontent.com/6940479/85183020-a31c6700-b28a-11ea-81c0-15cc1e90e41e.png)

I did a crude fix to that fork called olifant so we have a working client but this also affects your rewrite.

**Comment by ranfdev** [comment]
The situation should improve after applying #176

**Comment by bleakgrey** [comment]
I really wish I could make phoc compile. Adapting the UI would've been so much easier if I could actually see how it looks on them myself. :cry:

**Comment by bleakgrey** [comment]
Can you please check how `master` looks now?

**Comment by Alexmitter** [comment]
Hi, you can just use the qemu image provided by purism here: https://developer.puri.sm/Librem5/Development_Environment/Boards/qemu.html

I will test your changes in master today evening and give back my feedback.

**Comment by Alexmitter** [comment]
Hey, so I build it and it already is a big improvement.
I just wonder why your bars are all so big, I would have probably just take a libhandy csd buttons example and adapted it. But generally it seems like everything is bigger then it should be.

![new-tootle1](https://user-images.githubusercontent.com/6940479/85204197-18cc1580-b313-11ea-8eae-6cfbd0efe84c.png)


I hope the qemu image will work for you.

**Comment by bleakgrey** [comment]
I blame the avatars. Something's off in the way they calc their size, I think they are multiply the scaling factor twice or something. I'll look into it.

**Comment by bleakgrey** [comment]
This is as small as the window can possibly get resized. I *think* it should be fine now.
![Screenshot from 2020-06-30 00-40-14](https://user-images.githubusercontent.com/20158357/86059230-01a3cb00-ba6b-11ea-970f-cade0773f620.png)

**Comment by ranfdev** [comment]
Mmmmm... IDs (account id, status id...) are different between instances.
So... I think you can hide the account switcher btn when you show the back
btn. When the back btn is visible, probably you are viewing a specific
status or account, and you can't switch account while doing that anyway,
because the IDs of the elements you are viewing are different after
switching the account.

**Comment by bleakgrey** [comment]
@ranfdev I want to keep the ability to switch accounts at any time. IDs are indeed unique for each instance, but I don't think it matters because entities can be resolved by the instance by querying their URL.
