### ISSUE TITLE
Streaming notifications are added to bottom of notifications view

### ISSUE THREAD

**Issue by martensitingale** [bleakgrey/tootle#18]
They should appear at the top, of course.

I think this is due to `NotificationView.prepend` actually *appending* the status to the end of the list. It seems that `TimelineView.prepend`, similarly, actually appends the status to the end of the list, but unlike the notification view it has a boolean argument `first` which when passed true will prepend instead of appending.

Maybe appending/prepending to a view should be factored into a simple implementation shared between all views?

**Comment by bleakgrey** [comment]
Disregard function names, they're a relic from an early alpha. I'm going to restructure all of this mess in my multiple-accounts branch anyway.

Looks like I forgot to copy the Home timeline behavior for new data. Whoops.
