### ISSUE TITLE
Compose dialog doesn't fit on phone screens

### ISSUE THREAD

**Issue by atoft** [bleakgrey/tootle#183]
I got this to build on Mobian on the Pinephone, it looks great :) 
![2020-07-04-225452](https://user-images.githubusercontent.com/11033254/86521586-df36f680-be4a-11ea-8c36-e7f650906f31.png)

I'm able to log in and make it to the timelines, but I can't scroll in any of the views as every touch causes a toot to be opened. I'm guessing that the toots need to be only opened on release to make scrolling possible.

Let me know if I can help testing anything out.

**Comment by bleakgrey** [comment]
I'm surprised it took me so long to work out a solution, working with key press events in GTK is a bit counter-intuitive. The `master` branch should work properly now.

**Comment by bleakgrey** [comment]
Can you show me how a user profile looks on your device? It's unrelated to the issue, I'm just curious if the header bar looks okay on smaller screens.

**Comment by atoft** [comment]
Awesome, scrolling works with the latest master :) Reading the timelines works well now. The only issue I notice is that the scrolling gets weird if you are touching the screen when new toots are loaded (it will cause rapid up or down scrolling).

The user profile looks good to me:
![2020-07-05-104551](https://user-images.githubusercontent.com/11033254/86530532-5f904280-beb1-11ea-95eb-eb3e0d80b3da.png)

The only header bar I see a problem with is in the "new toot" dialog, the right hand buttons are off screen:
![2020-07-05-104324](https://user-images.githubusercontent.com/11033254/86530537-68811400-beb1-11ea-898c-38b427895d3e.png)

**Comment by bleakgrey** [comment]
Perhaps I should find another way to set minimum width for dialogs. That's doable.

The scrolling part is trickier though. Please create another issue concerning that and, If possible, include a video capturing that behavior (I'm aware of a few possible causes and need to see it to know which case that is).
