### ISSUE TITLE
Resolve view entities on instance switch

### ISSUE THREAD

**Issue by ranfdev** [bleakgrey/tootle#189]
**Problem**:
If you switch account inside views requiring instance-specific IDs, everything breaks: sometimes inconsistent data will be loaded, sometimes nothing can be loaded at all, because the corresponding ID in the new instance doesn't exist.

**How to reproduce:**
1. Add 2 accounts to tootle. **They must be from different instances**
2. Open the profile of someone
3. Switch to an account in a different instance.

**Screenshots:**
Before switching account (everything is correct here):
![Screenshot from 2020-07-08 11-22-19](https://user-images.githubusercontent.com/23294184/86901890-81860100-c10d-11ea-9c2a-d1583f92c40b.png)
After switching accounts:
![Screenshot from 2020-07-08 11-22-30](https://user-images.githubusercontent.com/23294184/86901917-8a76d280-c10d-11ea-8f1e-6ab695043373.png)

**Comment by ranfdev** [comment]
I understand being able to switch accounts from everywhere can be useful, but it's just not possible, unless you map the IDs between instances (but I have no idea on how to implement this).

**Comment by bleakgrey** [comment]
There's no need to use IDs. Account and status entities contain the `url` field which can be resolved by the instance (confirmed to work through the Search view).

To implement this behavior, all it would take is introduce an invalidation mechanism that checks if the instance has changed, ask the new instance to resolve the entity by its `url`, and replace it with the response.
