### ISSUE TITLE
Headerbar height

### ISSUE THREAD

**Issue by bertob** [bleakgrey/tootle#194]
Looks like there's something odd happening with the headerbar height, it's a few pixels taller than other apps.

![image](https://user-images.githubusercontent.com/1908896/87228399-4a2f8280-c3a1-11ea-8460-e81272a2068c.png)

Here's a zoomed-in screenshot showing the issue more clearly:

![image](https://user-images.githubusercontent.com/1908896/87228367-17858a00-c3a1-11ea-943b-4194b0b123f2.png)

**Comment by bleakgrey** [comment]
Can't reproduce. Is that Clocks nightly?
![Screenshot from 2020-07-12 12-45-15](https://user-images.githubusercontent.com/20158357/87243318-b3fd6a00-c43d-11ea-9a75-09b60034ea64.png)
