### ISSUE TITLE
Use small text for secondary information

### ISSUE THREAD

**Issue by bertob** [bleakgrey/tootle#196]
Currently all text within the toot widget uses the regular text size, which means it's all competing for attention at the same level.

![image](https://user-images.githubusercontent.com/1908896/87229241-e0b27280-c3a6-11ea-8deb-0e279f450fcf.png)

If you look at other clients, secondary information uses a smaller text size, so the actual toot content is more prominent:

![image](https://user-images.githubusercontent.com/1908896/87229274-13f50180-c3a7-11ea-87c9-9fc52eb5c4cc.png)

I'd suggest having the following things use the small text size:

- @ username
- timestamp
- "X boosted" label above the toot

**Comment by bleakgrey** [comment]
What about the baseline alignment to compensate for the size difference?

**Comment by bertob** [comment]
Baseline alignment of what?

**Comment by bertob** [comment]
Actually, I just noticed that the text size on posts is larger than the default UI font size?

**Comment by bleakgrey** [comment]
![Screenshot from 2020-07-11 21-48-07](https://user-images.githubusercontent.com/20158357/87231499-80c8c580-c3c0-11ea-970b-3521ff2d3319.png)


If the size is decreased, the vertical alignment becomes uneven. Should the labels centered? Packed to the top or the bottom line?

**Comment by bleakgrey** [comment]
Yes, the text size in timelines is slightly bigger by default since some people have complained about it being too small and unreadable. It is configurable in the settings.

**Comment by bleakgrey** [comment]
Here is how it looks like on my setup with the scaling disabled

![Screenshot from 2020-07-11 21-53-06](https://user-images.githubusercontent.com/20158357/87231582-f9c81d00-c3c0-11ea-9bcb-46f2d81a72aa.png)

**Comment by bertob** [comment]
> Yes, the text size in timelines is slightly bigger by default since some people have complained about it being too small and unreadable. It is configurable in the settings.

I'd change the default to off on that. If the standard text size in this app is too small then the text across the entire system is too small, no? This is what the system-wide "large text" a11y setting is for :)

And yes, aligning the baselines would be good.

**Comment by ranfdev** [comment]
Yes please, don't make the text bigger by default. It's really akward. For
a moment I even thought there was something wrong with my setup.
