### ISSUE TITLE
Tootle counts bytes instead characters, which is incorrect.

### ISSUE THREAD

**Issue by veer66** [bleakgrey/tootle#198]
**What should happen:**
In tooting window, after typing one character, i.e., ก, the counter should show 499.

**What happened instead:**
In tooting window, after typing one character, i.e., ก, the counter should show 497.

**How to reproduce:**
1. Click at pencil icon
2. In textbox, type ก

**Screenshots:**

![image](https://user-images.githubusercontent.com/370688/87632253-2da99680-c763-11ea-9cd9-78e9e70ef658.png)

**Build context:**
 - Distro: Fedora 32  
 - Version: 0.2.0
 - Build type: Flatpak

**Comment by thep** [comment]
Use string `char_count()` instead of `length`?

```diff
Index: tootle-0.2.0/src/Dialogs/PostDialog.vala
===================================================================
--- tootle-0.2.0.orig/src/Dialogs/PostDialog.vala
+++ tootle-0.2.0/src/Dialogs/PostDialog.vala
@@ -168,9 +168,9 @@ public class Tootle.PostDialog : Gtk.Dia
     }
     
     private void validate () {
-        var remain = char_limit - text.buffer.text.length;
+        var remain = char_limit - text.buffer.text.char_count();
         if (spoiler.active)
-            remain -= spoiler_text.buffer.text.length;
+            remain -= spoiler_text.buffer.text.char_count();
         
         counter.label = remain.to_string ();
         publish.sensitive = remain >= 0; 
```
