### ISSUE TITLE
tag pre-1.0 version

### ISSUE THREAD

**Issue by okias** [bleakgrey/tootle#207]
Hello @bleakgrey 

thank you for nice progress on Tootle, I'd like to give a shot to update Debian package when 1.0 version will be released, but until then, could you release some alpha/beta (0.99.1 / 0.99.98 or something like that)?

P.S. just tested git version and I must say impressive progress!

**Comment by bleakgrey** [comment]
Sure thing. I'll fix some critical bugs and release an alpha.

**Comment by okias** [comment]
Don't forget please. It's almost month and I think you could eventually release even beta.

**Comment by bleakgrey** [comment]
I remember about this. I'm working on Tootle when I have free time, which is not much due to the 2020 events ¯\_(ツ)_/¯

The amount of work left to be done is extremely small, please have patience.

**Comment by bleakgrey** [comment]
Wish granted~ :sparkles:
