### ISSUE TITLE
Design : Search button in headerbar

### ISSUE THREAD

**Issue by lionirdeadman** [bleakgrey/tootle#216]
Most GNOME apps use this location and it makes more sense than clicking it as an option in the account pop-over, I think.

**Comment by bleakgrey** [comment]
1.0 is supposed to perform well on smaller phone screens, so I don't have the luxury of packing more buttons into the header bar anymore. 

Even though the current header bar design is frozen for now, I'm free to add plenty of keyboard shortcuts.

**Comment by lionirdeadman** [comment]
> 1.0 is supposed to perform well on smaller phone screens, so I don't have the luxury of packing more buttons into the header bar anymore.
> 
> Even though the current header bar design is frozen for now, I'm free to add plenty of keyboard shortcuts.

But you're already moving all the buttons in a bottom bar which leaves the headerbar mostly empty on smaller screens as mentioned in #195.

**Comment by bleakgrey** [comment]
If we're talking about _global_ search (posts, accounts, hashtags), it makes no sense to display this button _on every view_ as it's not even related to it. It's not filtering the timeline content, it's resolving instance entities.

Besides, even if it could work for Home screen (I'll admit, it's pretty empty), I can't move Profile's header bar content to the bottom bar. Even its title barely fits there.

**Comment by lionirdeadman** [comment]
Hm, yeah, in every view it wouldn't make sense. Maybe just Home. I still think it is strange to put it in the account pop-over.
