### ISSUE TITLE
Tooltip hovering is broken in the account pop-over

### ISSUE THREAD

**Issue by lionirdeadman** [bleakgrey/tootle#219]
⚠️ Please try to fill in every blank. Keep the information clear and concise.

#### What should happen:
They should appear normally

#### What happened instead:
They flicker

#### How to reproduce:
1. Open account pop-over
2. Hover over the icon options
#### Build context:
 - **Distro:** Fedora 32
 - **App version:** master-git
 - **Build type:** Flatpak

**Comment by bleakgrey** [comment]
Do you mean the circle ones? Their tooltips seem to work just fine on Pop_OS :/

**Comment by bleakgrey** [comment]
If you can, please record a video

**Comment by lionirdeadman** [comment]
Yes, the circle ones.



![Screencast from 2020-08-05 12_52_17 PM](https://user-images.githubusercontent.com/39467792/89441966-fbfd6d00-d71b-11ea-8fc8-88a9bfb82d86.gif)

**Comment by bleakgrey** [comment]
Interesting. I'll test it inside Flatpak.

**Comment by bleakgrey** [comment]
I give up. I can't reproduce this :/

**Comment by lionirdeadman** [comment]
Well, that's good, I can't either. Haha.
