### ISSUE TITLE
Post creation window is too wide for phone.

### ISSUE THREAD

**Issue by Baggypants** [bleakgrey/tootle#221]
#### What should happen:
__
When on a mobile screen and you click the new post button the resulting window should be narrow enough to fit on the screen.

#### What happened instead:
__
The post creation window is too wide and the post button on the far right cannot be clicked.

#### How to reproduce:
1. Open tootle on a mobile device (720x1440)
2. Click the pencil!

#### Screenshots (if applicable):

[Screnshots](https://imgur.com/a/x16ehKP)

#### Build context:
 - **Distro:** Mobian
 - **App version:** 0.2.0+20200712-1mobian1
 - **Build type:** Built by a third-party maintainer

#### Logs:
*(Terminal logs are often invaluable. If you can, launch the app from terminal with `com.github.bleakgrey.tootle` and paste the output here)*

#### Additional info (if needed):
I've got a pinephone
it's got an app on it
it makes me happy
happy that I've got it.

**Comment by bleakgrey** [comment]
@atoft Did I break the master again? I thought we already fixed that :c

**Comment by bleakgrey** [comment]
I just looked up the sources in the Mobian's repos.

Mobian's Tootle was last updated on July 12th, which is slightly outdated. I'm pretty sure that the latest `master` branch has this minor inconvenience fixed.

Please ask the maintainer to update the package.

**Comment by bleakgrey** [comment]
(thank you for using Tootle, by the way ❤️)
