### ISSUE TITLE
Feature request: new release

### ISSUE THREAD

**Issue by FedericoCeratto** [bleakgrey/tootle#222]
Hello @bleakgrey and thank you for developing Tootle!
Could you please consider making a new release?

The last release is from 2018 and is affected by various bugs:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?repeatmerged=no&src=tootle

Also, the addition of libhandy should improve usability on touch devices (e.g. PinePhone with Mobian)

**Comment by bleakgrey** [comment]
As stated in #207, I'm aiming to release a pre-1.0 version pretty soon. There's still a couple of bugs left to fix.

**Comment by FedericoCeratto** [comment]
Thanks!
