### ISSUE TITLE
Improve HTML parsing for post content

### ISSUE THREAD

**Issue by bleakgrey** [bleakgrey/tootle#235]
Integration with Pleroma makes the current post content sanitation method no longer rational (see #233).

The post widget should use separate widgets for `p`, `code`, `img`, and similar tags packed inside a Gtk.Box instead of using a single RichLabel widget and regex spaghetti code to make Pango happy.

- [ ] Find a library to parse HTML
- [ ] Introduce a new `MarkupParser` class that takes a raw HTML string, parses it and injects one or more widgets into a Gtk.Box
- [ ] Optional: Find a way to insert images into a Label widget (Will be useful for instance emojis too)

**Comment by dec05eba** [comment]
`Optional: Find a way to insert images into a Label widget (Will be useful for instance emojis too)`
I dont know if that is possible with labels, but its possible with gtk TextView. TextView allows you to puts widgets in the middle of the text. There is an example under Text View -> Multiple Views in the gtk3-demo program (which should be installed on your system if you have gtk3 installed) which has an example which combines text, images and other widgets in the text.

**Comment by bleakgrey** [comment]
@dec05eba Labels do support custom drawing and I had a working demo somewhere on my old laptop. It had something to do with the Label's `attributes` param. Sadly, its HDD died and I don't have a backup. I'll investigate this later.

**Comment by bleakgrey** [comment]
There, I found this in my bookmarks: https://gist.github.com/andymeneely/f21a39fce8008459da6f9ec52faea38f. I'll leave it here just in case because nothing is safe near me.
