### ISSUE TITLE
Avatar widget should not extend Gtk.Button

### ISSUE THREAD

**Issue by Kekun** [bleakgrey/tootle#238]
⚠️ Please try to fill in every blank. Keep the information clear and concise.

#### What should happen:
The clip area of the user's avatar (in the button in the header bar) should be consistent and always show the full avatar.

#### What happened instead:
The clip area of the user's avatar is too wide when Tootle's window is focused, and too small when the window isn't, making it be cut.

#### How to reproduce:
1. Ensure the avatar is visible in Tootle's window
2. Toggle the focus between Tootle's main window and another

#### Screenshots (if applicable):
WTF GitHub doesn't accept videos‽ Uuuh…

![Capture d’écran de 2020-09-16 09-09-49](https://user-images.githubusercontent.com/2536339/93303888-6ebe3580-f7fc-11ea-96a2-6738976ea6ac.png)

![Capture d’écran de 2020-09-16 09-09-52](https://user-images.githubusercontent.com/2536339/93303890-7087f900-f7fc-11ea-92cb-1c099beaec5f.png)

#### Build context:
 - **Distro:** Fedora Silverblue
 - **App version:** 1.0-alpha1 + a few commits, but the issue was there way before
 - **Build type:** Built from Flatpak

#### Logs:
Nothing that seems relevant.

#### Additional info (if needed):
Nothing.

**Comment by BrainBlasted** [comment]
You could use HdyAvatar here in the main window (and in other areas where an Avatar is shown)
