### ISSUE TITLE
Clicking on Attachments crashes

### ISSUE THREAD

**Issue by LibreHacker** [bleakgrey/tootle#240]
`-> Pixbuf: FAIL (Server returned 403: Forbidden)`

later ~ 5 seconds

```
No such file or directory

Segmentation fault
```

System - Arch Linux

**Comment by bleakgrey** [comment]
Can you post the detailed logs? I can't quite piece together what exactly happened here.

**Comment by LibreHacker** [comment]
```
** (com.github.bleakgrey.tootle:2280): WARNING **: 17:31:24.418: Cache.vala:97: "url.com/filename.(gif/.png)"-> Pixbuf: FAIL (Server returned 403: Forbidden)
** (com.github.bleakgrey.tootle:2280): WARNING **: 17:31:32.947: Desktop.vala:75
Error: Error creating directory /home/username/Downloads/Tootle/url.com: No such file or directory

Segmentation fault
```
It's all what i see.

**Comment by bleakgrey** [comment]
Did Tootle crash when you tried to open an attachment?

**Comment by LibreHacker** [comment]
> Did Tootle crash when you tried to open an attachment?

Yes

**Comment by bleakgrey** [comment]
Next time, please use the "Bug Report" template that already contains all the questions needed to pinpoint the problem.

**Comment by dduenker** [comment]
Had the same issue, solved it by creating the directory `~/Downloads/Tootle/`.
Apparently tootle expects it to exist and does not create it, when needed.

**Comment by marek-lach** [comment]
Related: 204

Tootle needs to have an option not to open/download every media attachment it stumbles upon.
