### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by allnamesaretakeningithub** [bleakgrey/tootle#243]
#### What should happen:
__

All dialog windows: Account setup (text field for instance address and for imput the access token) and compose a post/toot should adapt to fit in different form factors, desktop, tablet, a 5 inch phone screen (Librem 5, Pinephone).

And the dialogs should use the system windows so that they are not hidden behind the virtual keyboard (in the case of Linux phones)  

#### What happened instead:

- Both the account setup and compose a toot windows exceed the window with of the Librem 5, (and probably the same on a Pinephone, but this is not tested). This makes it difficult to press the buttons on the corners of the top bars. Also when you type part of the window is hidden behind the virtual keyboard.

#### How to reproduce:
1. Install Tootle on a device using phosh, for example a qemu image: https://developer.puri.sm/Librem5/Development_Environment.html
2. Setup account and credentials and make a post

#### Screenshots (if applicable):

![2020-09-18-150942](https://user-images.githubusercontent.com/15075989/93606252-176cc080-f9c8-11ea-8c46-c9b40dee43de.png)

![2020-09-18-151048](https://user-images.githubusercontent.com/15075989/93606270-1d62a180-f9c8-11ea-990b-4af98b98642b.png)
![2020-09-18-151845](https://user-images.githubusercontent.com/15075989/93606273-1e93ce80-f9c8-11ea-8de7-15a0a90a4ad5.png)
![2020-09-18-152212](https://user-images.githubusercontent.com/15075989/93606276-1f2c6500-f9c8-11ea-9ea3-746874f058a5.png)
![2020-09-18-152231](https://user-images.githubusercontent.com/15075989/93606277-1fc4fb80-f9c8-11ea-8cb1-e16de58549fc.png)
![2020-09-18-152301](https://user-images.githubusercontent.com/15075989/93606284-205d9200-f9c8-11ea-9e66-32f6c54d628e.png)

__

#### Build context:
 - **Distro:** PureOS for the Librem 5
 - **App version:** __

```
Tootle - Lightning fast client for Mastodon

          ID: com.github.bleakgrey.tootle
         Ref: app/com.github.bleakgrey.tootle/aarch64/stable
        Arch: aarch64
      Branch: stable
     Version: 1.0.0-alpha1
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1,8 MB
     Runtime: org.gnome.Platform/aarch64/3.36
         Sdk: org.gnome.Sdk/aarch64/3.36

      Commit: c401ae7a67331a139f08e25d4c5b3f7518c3e224f9dbfa9dfbf292653b22349a
      Parent: 75021dde72cda535ab9215bb4be1f573f6428c790a454f0763ca358c3680324f
     Subject: Update manifest (4b183285)
        Date: 2020-09-11 18:56:44 +0000

```

 - **Build type:** Flatpak 

#### Logs:
*(Terminal logs are often invaluable. If you can, launch the app from terminal with `com.github.bleakgrey.tootle` and paste the output here)*

#### Additional info (if needed):
__

Some of these issues are likely due to the faltpak version not using specific GTK patches for `phosh`

**Comment by bleakgrey** [comment]
Moving to #269
