### ISSUE TITLE
[Papercuts] small visual issues on account setup

### ISSUE THREAD

**Issue by spaetz** [bleakgrey/tootle#247]
This is using 0.2.0+20200712-1mobian1
On both the screens where you enter you enter your host instance and your AUTH credentials, hitting <ENTER> in the text field will not work, ie advance to the next stage. It would be great if it did, because I thought something was frozen.

This is made harder by the fact that the "forward" button is not visible when the keyboard is on (which it is by default), and I have to close the keyboard before being able to discover and hit the "next" button.
![tootle](https://user-images.githubusercontent.com/63132/94111405-4cec3080-fe44-11ea-9b33-1e69820b3f25.png)

So I guess, this is 2 issues really:
1) Make <ENTER> work to enable keyboard only navigation
2) Make the screen even more flexible so the "next" button is not forced underneath the keyboard.

Thanks for tootle!

UPDATE: I just discovered that this is not the latest alpha release, so bear with me if this has been fixed already. An example of how it could look like is fractal:
![2020-09-24-071229](https://user-images.githubusercontent.com/63132/94118223-82e1e280-fe4d-11ea-824a-11f1c386c957.png)

**Comment by spaetz** [comment]
DOH, I have now pulled and tested 1.0alpha1 and it basically looks like the fractal one now, and <ENTER> works too. I herewith retract my issue and apologize for the noise :+1:

**Comment by bleakgrey** [comment]
That's okay, thanks for testing!
