### ISSUE TITLE
Use HdyAvatar

### ISSUE THREAD

**Issue by Kekun** [bleakgrey/tootle#248]
At GNOME we just created the Avatar Consistency initiative, which tries to make avatars look consistent across all GNOME apps by simply using `HdyAvatar`, see: https://gitlab.gnome.org/GNOME/Initiatives/-/issues/20

That would be great if Tootle used it too! :)

**Comment by bleakgrey** [comment]
Does `Hdy.Avatar` really have to be declared final? I needed some custom logic for `Account` entity binding, and valac found it impossible to inherit from the widget class. I wrapped it with a `Gtk.Bin` instead.

I personally find the class being final more of a minor inconvenience than a necessity. Is there something I'm missing?
