### ISSUE TITLE
Port to GTK4

### ISSUE THREAD

**Issue by bleakgrey** [bleakgrey/tootle#254]
Oof.

**Comment by BrainBlasted** [comment]
Some examples of ports:

* https://gitlab.gnome.org/World/Solanum/-/merge_requests/22
* https://gitlab.gnome.org/World/Social/-/merge_requests/
* https://gitlab.gnome.org/World/podcasts/-/merge_requests/173
* https://gitlab.gnome.org/haecker-felix/gnome-store/-/merge_requests/18 + https://gitlab.gnome.org/haecker-felix/gnome-store/-/merge_requests/21

A Vala app written in GTK4 to start with:

* https://github.com/nahuelwexd/Replay/

For libhandy, use https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/625

**Comment by BrainBlasted** [comment]
An issue of relevance within GTK: https://gitlab.gnome.org/GNOME/gtk/-/issues/3280#note_939055

There's also https://gnome.pages.gitlab.gnome.org/gtk/gtk/gtk-migrating-3-to-4.html to review - https://gnome.pages.gitlab.gnome.org/gtk/gtk/ is the place to look at docs while GTK4 is still "unstable"
