### ISSUE TITLE
Windows don't fit the mobile screen

### ISSUE THREAD

**Issue by dos1** [bleakgrey/tootle#269]
The "Add Account" window's minimal width exceeds 360 pixels, resulting in overgrown window on mobile phones.

#### Screenshots (if applicable):
![tootle2](https://user-images.githubusercontent.com/126204/102273871-4b9e4180-3f23-11eb-91af-b07836b2ada9.png)
![tootle3](https://user-images.githubusercontent.com/126204/102274243-d8e19600-3f23-11eb-9292-64f5e151a9f1.png)

#### Build context:
 - **Distro:** PureOS Amber-phone
 - **App version:** 1.0-alpha2
 - **Build type:** Built from source

**Comment by bleakgrey** [comment]
Welp, I broke it again :')

**Comment by dos1** [comment]
@bleakgrey I found more screens that don't fit - do you want a separate issue for each of them?

**Comment by bleakgrey** [comment]
Let's make this issue a list. Which ones are broken too?

**Comment by dos1** [comment]
User profile view:
![tootle4](https://user-images.githubusercontent.com/126204/102279623-00d4f780-3f2c-11eb-993f-1c06a3a3254a.png)

Creating a new list:
![tootle5](https://user-images.githubusercontent.com/126204/102279687-1ba76c00-3f2c-11eb-80f1-27545df8a022.png)

That's all I found so far :)
