### ISSUE TITLE
LiberaPay does not accept donations

### ISSUE THREAD

**Issue by chri2** [bleakgrey/tootle#271]
LiberaPay does not accept donations for bleakgrey

**Comment by bleakgrey** [comment]
Yeah, LiberaPay routes payments through either PayPal or Stripe. The latter doesn't work in Russia, and PayPal isn't being too kind to me now either. I'll post an update on my Mastodon account when I've sorted out this inconvenience.

Isn't really a bug, so I'm going to close this.

**Comment by bleakgrey** [comment]
I do appreciate the gesture, btw :)
