### ISSUE TITLE
More semantic "star" icons

### ISSUE THREAD

**Issue by cassidyjames** [bleakgrey/tootle#29]
Instead of using `help-about-symbolic`, you should probably use and toggle between `non-starred-symbolic` and `starred-symbolic`. That way it looks as expected if the elementary icons ever change.

**Comment by bleakgrey** [comment]
Those icons are colored on elementary and look a bit out of place to me. It feels like boosted toggle button should be colored too :/

**Comment by cassidyjames** [comment]
@bleakgrey that's just the default color palette; you should be able to override it with CSS by setting the `-gtk-icon-palette: success #333, warning #333, error #333;` if you want to set the color to `#333`, for example.

**Comment by bleakgrey** [comment]
Looks like this property is only available in GTK >=3.20, so I'm going to leave the current icon for now

**Comment by bleakgrey** [comment]
Changing this in the next version
