### ISSUE TITLE
Slow to resize

### ISSUE THREAD

**Issue by bugaevc** [bleakgrey/tootle#293]
#### What should happen:
Tootle window should resize at 60 FPS (or more)

#### What happened instead:
Tootle window was very slow to resize, taking multiple seconds to render each frame. That, and while resizing, it was also jumping left and right.

#### How to reproduce:
1. Open Tootle
2. Make sure you're logged into your account
3. Try to resize the window

#### Build context:
 - **Distro:** Fedora 34
 - **App version:** 1.0.0
 - **Build type:** Flatpak

**Comment by bugaevc** [comment]
This will probably get magically fixed with the gtk4 port.

**Comment by bleakgrey** [comment]
Magically fixed with the gtk4 port :D
