### ISSUE TITLE
30% CPU when idle

### ISSUE THREAD

**Issue by bugaevc** [bleakgrey/tootle#297]
I left Tootle open, idle. I took a peek at `htop`, and it seems like Tootle is using around 30% of a CPU core when completely idle.

#### Build context:

- Distro: Fedora 34
- App version: 1.0.0
- Build type: Flatpak

**Comment by bleakgrey** [comment]
Oof

**Comment by bleakgrey** [comment]
Can't reproduce in master anymore, please open this again if still relevant.

**Comment by bugaevc** [comment]
But have you been able to reproduce this before?

**Comment by bleakgrey** [comment]
Not at all. It *may* have something to do with flatpak, I mainly use native builds.

23 июля 2021 г. 15:46:45 GMT+03:00, Sergey Bugaev ***@***.***> пишет:
