### ISSUE TITLE
Tapping on Images Crashes Tootle on Mobian

### ISSUE THREAD

**Issue by Simmonz** [bleakgrey/tootle#301]
When I use Tootle on my Pinephone which is running Mobian it works just fine for anything I try until I tap on an image to expand it. This causes Tootle to crash without any error on screen.

#### What should happen: The image should expand to fullscreen
__

#### What happened instead: Tootle crashes closed
__

#### How to reproduce:
1. Open Tootle on Mobian
2. _Tap on any image

#### Screenshots (if applicable):
The app crashes as soon as I tap on an image so a screenshot is not possible

#### Build context:
 - **Distro:** Mobian
 - **App version: 1.0.0-alpha2
 - **Build type: Installed from Software app on Mobian

#### Logs:

[log.txt](https://github.com/bleakgrey/tootle/files/6330504/log.txt)

#### Additional info (if needed):
Pinephone Convergence: Mobian | Gnome 3.38.4 | 5.10-sunxi64

**Comment by bleakgrey** [comment]
This issue has been resolved in 1.0 stable.

**Comment by CaptainMorgan12** [comment]
Same issue on PureOS crashes with pictures and videos. App simply disappears on click on image or video?
