### ISSUE TITLE
[Feature request / Design suggestion]

### ISSUE THREAD

**Issue by Merazi** [bleakgrey/tootle#305]
What about moving the Refresh option from the menu to a button on the main toolbar? Maybe next to the compose button.

**Comment by bleakgrey** [comment]
I don't find it necessary. The header bar is already cluttered as it is, and adding another (rather unpopular) button will certainly break things on phones. 

Tootle streams timelines by default, so there's really no need for this button to be visible all the time. If really, _really_ needed, there's this menu option and the `Ctrl+R` shortcut present.
