### ISSUE TITLE
Can't connect to pleroma server

### ISSUE THREAD

**Issue by noccio** [bleakgrey/tootle#308]
I can't connect to a pleroma server that it is working fine with other clients.

If I try to register with the "Add account" window I get a "400: Bad request" error.

This is the log in terminal:

    ** Message: 18:09:21.027: Build.vala:32: Tootle 1.0.0-alpha2
    ** Message: 18:09:21.027: Build.vala:33: Running on: Debian GNU/Linux 10 (buster)

    ** Message: 18:09:21.027: Build.vala:34: Build prefix: "/usr"
    ** Message: 18:09:21.442: Accounts.vala:134: Loaded 0 accounts
    ** Message: 18:09:21.450: Application.vala:147: Presenting NewAccount dialog
    ** Message: 18:09:21.583: NewAccount.vala:76: Reset state
    ** Message: 18:09:30.487: NewAccount.vala:116: Checking instance URL
    ** Message: 18:09:30.488: NewAccount.vala:131: Registering client
    ** Message: 18:09:30.602: NewAccount.vala:58: Successfully associated MIME type for automatic authorization

    ** (tootle:1508201): CRITICAL **: 18:09:30.604: string_to_string: assertion 'self != NULL' failed

    ** (tootle:1508201): WARNING **: 18:09:38.207: NewAccount.vala:90: Server returned an error   400: Bad Request

**Comment by bleakgrey** [comment]
`1.0.0-alpha2` doesn't support Pleroma instances. In fact, it's still WIP and likely to land when Tootle is ported to GTK4.
