### ISSUE TITLE
Doesn't build using the Flatpak manifest

### ISSUE THREAD

**Issue by YaLTeR** [bleakgrey/tootle#314]
#### What should happen:
It builds and runs fine.

#### What happened instead:
First the GTK 4 meson dependency is `>=4.3.0` whereas the runtime from the manifest (`org.gnome.Platform//40`) only has `4.2.1`. After fixing that, I get the following error:
```
../../../../../../../../../source/vala/tootle/src/Dialogs/Composer/Dialog.vala:35.13-35.33: error: The type name `Adw.ViewStack' could not be found
	[GtkChild] unowned Adw.ViewStack stack;
	           ^^^^^^^^^^^^^^^^^^^^^
../../../../../../../../../source/vala/tootle/src/Views/TabbedBase.vala:9.12-9.24: error: The type name `Adw.ViewStack' could not be found
	protected Adw.ViewStack stack;
	          ^^^^^^^^^^^^^
```

#### How to reproduce:
1. Clone in Builder and press Run.

#### Build context:
 - **Distro:** Fedora 34 Silverblue
 - **App version:** f774eb9
 - **Build type:** Flatpak

**Comment by bleakgrey** [comment]
Ah, right. I forgot to update the manifest.
