### ISSUE TITLE
Tootle not in AppCenter anymore

### ISSUE THREAD

**Issue by JohnDumpling** [bleakgrey/tootle#319]
After the release of Elementary OS 6, Tootle is no longer available in the AppCenter. After installing a random Flatpak app from Flathub, the repository is added to the AppCenter and Tootle shows up as a non-curated app. There used to be a Tootle app with Elementary stylesheet, but that version is not there anymore. Could you please publish this app to AppCenter? Many thanks.

**Comment by bleakgrey** [comment]
This behavior is intended. Since the latest release, Tootle has switched its platform and is targeting GNOME now.

If you want to use the old "elementary style" interface, you can try [Olifant](https://github.com/cleac/olifant), but it looks like it's discontinued too.
