### ISSUE TITLE
Implement "Watchlist"

### ISSUE THREAD

**Issue by cassidyjames** [bleakgrey/tootle#33]
I'm not sure if this is something exposed via the API, or if it would have to be all client-side. But getting notifications when specific users toot would be awesome. For example, if I follow a low-volume but high-quality account, some sort of emergency or status account, or an account during a giveaway.

**Comment by bleakgrey** [comment]
Getting notifications from specific users would require polling their profiles and tracking new toots. Not available through real-time push API I believe.

**Comment by bleakgrey** [comment]
Or do you mean notifications per authorized account in the app?

**Comment by bleakgrey** [comment]
Well technically I can display a custom notification if a toot from a specific user appears in the home timeline, but it would require following that user. 

It makes sense to follow users you'd like to receive notifications from, right?

**Comment by cassidyjames** [comment]
@bleakgrey ah yeah I think on Twitter you can only get notifications for people you follow.
