### ISSUE TITLE
Avatars tiny on HiDPI

### ISSUE THREAD

**Issue by cassidyjames** [bleakgrey/tootle#35]
It's so itty bitty!

![image](https://user-images.githubusercontent.com/611168/40872463-db2c36de-660b-11e8-94e4-53e7e69c6844.png)

**Comment by cassidyjames** [comment]
Yep, GTK widgets have a `scale_factor` property.

**Comment by cassidyjames** [comment]
https://valadoc.org/gtk+-3.0/Gtk.Widget.scale_factor.html

**Comment by bleakgrey** [comment]
I wish Granite avatars handled that automatically. I have to manually download, resize and write them to PixBufs. If I don't, then... well...

![screenshot from 2018-06-02 12-04-09](https://user-images.githubusercontent.com/20158357/40872811-96e07bbe-665d-11e8-9eef-b62e2a050a7d.png)

**Comment by cassidyjames** [comment]
Ha, yikes! That does sound like the right way to do it, at least from peeking at the Wingpanel Session Indicator:

https://github.com/elementary/wingpanel-indicator-session/blob/8a40a13a17afca60f85109edbc4fe4ec220f1639/src/Widgets/UserBox.vala#L107

**Comment by cassidyjames** [comment]
But yeah, maybe open an issue on Granite if there's a sane way to make that easier.

**Comment by bleakgrey** [comment]
Can you check if it's behaving properly in the master branch? My screen isn't HiDPI so I can't verify it myself.

**Comment by cassidyjames** [comment]
@bleakgrey you can set the scaling factor in the GTK inspector to try it out, but I'll also give it a try on HiDPI when I can!

**Comment by cassidyjames** [comment]
I think this looks correct on HiDPI now

![image](https://user-images.githubusercontent.com/611168/40882117-a5413b70-6695-11e8-92bb-ebd629a65e83.png)

**Comment by cassidyjames** [comment]
Fixed by #35
