### ISSUE TITLE
Gnome 40 flatpak runtime no longer supported

### ISSUE THREAD

**Issue by doczipeter** [bleakgrey/tootle#351]
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.bleakgrey.tootle

says flatpak on the command line.

**Comment by harmathy** [comment]
This issue is already covered by flathub/com.github.bleakgrey.tootle/issues/18
