### ISSUE TITLE
Default Post Location

### ISSUE THREAD

**Issue by ghost** [bleakgrey/tootle#36]
This might clutter things up a little bit, so maybe it is out of the question.

Could there be a way in settings to set the default audience you want? Such as, I want to post only to my instance timeline instead of posting globally by default. 

This is just a wishlist item.

**Comment by bleakgrey** [comment]
I think I can put it under the timelines settings

**Comment by h4ck3r9** [comment]
I was hoping this would be an easy enhancement. I hate asking for things from people. :)

**Comment by bleakgrey** [comment]
It is easy :D
Haha, why not? It's not like you're asking for something impossible. If Masto provides this feature, there's nothing against putting it in a Masto client.
