### ISSUE TITLE
Use same icons for boost

### ISSUE THREAD

**Issue by cassidyjames** [bleakgrey/tootle#39]
Looks like an up arrow is still used when showing someone else boosted. The site uses the same icon for the button and the status.

![screenshot from 2018-06-03 10 34 51](https://user-images.githubusercontent.com/611168/40888797-c9ffc9b6-6719-11e8-88e5-c04ded43291d.png)

![screenshot from 2018-06-03 10 37 43](https://user-images.githubusercontent.com/611168/40888817-2dc9034a-671a-11e8-92dc-b6737e966d00.png)

**Comment by bleakgrey** [comment]
Oh right, I use them twice...
