### ISSUE TITLE
Settings schema 'com.github.bleakgrey.tootle' is not installed

### ISSUE THREAD

**Issue by lanodan** [bleakgrey/tootle#41]
* [build.log](https://github.com/bleakgrey/tootle/files/2070242/build.log)
* Operating System: Gentoo

```
$ com.github.bleakgrey.tootle
[INFO 01:04:04.125741] Application.vala:154: Tootle version: 0.1.3
[INFO 01:04:04.125907] Application.vala:156: Kernel version: 4.14.14-gentoo
[ERROR 01:04:04.253848] [GLib-GIO] Settings schema 'com.github.bleakgrey.tootle' is not installed
Trace/breakpoint trap
```

I have this bug both with 2756afe (master now) and 0.1.3.

**Comment by bleakgrey** [comment]
Weird. The settings schema is explicitly installed during building, at least it should be. Try running `sudo glib-compile-schemas /usr/share/glib-2.0/schemas`.

**Comment by bleakgrey** [comment]
If that doesn't help, try building with default `/usr` prefix, maybe it has hard time finding it on non-Ubuntu based distros

**Comment by lanodan** [comment]
Installed it system-wide by doing a quick gentoo ebuild, and it works. Doing ``glib-compile-schemas`` as SuperUser didn’t work.

Can you look if installing it in the home would be possible?

**Comment by bleakgrey** [comment]
I'm sure that Tootle doesn't contain any path-specific components. It looks like it's GLib schema being finicky for a reason I fail to see.

**Comment by stevenroose** [comment]
I'm also getting this. I'm trying to just build into the `./build` directory instead of into `/usr`.
