### ISSUE TITLE
Background-color of highlighted posts should be theme-aware

### ISSUE THREAD

**Issue by tastytea** [bleakgrey/tootle#43]
I use a dark theme and highlighted posts are very hard to read.
![screenshot_2018-06-05t16 35 57](https://user-images.githubusercontent.com/3681516/40982967-154a296a-68ce-11e8-898a-9da248ea26fe.png)

**Comment by bleakgrey** [comment]
The background color is rgba and should be almost transparent :/

What OS are you using?

**Comment by tastytea** [comment]
I'm using Gentoo and GTK+-3.22.29. Has the transparency something to do with the window manager / compositor? I'm using i3 together with compton.

**Comment by bleakgrey** [comment]
Yes, it might be the issue. Can you try another one to see if anything changes?

**Comment by tastytea** [comment]
It's the same with XFCE 4.12.

**Comment by tastytea** [comment]
Oops, I just found out that there are settings in tootle and that I can select "Dark theme". m( 
There's no problem, sorry!
