### ISSUE TITLE
Escape more characters

### ISSUE THREAD

**Issue by tastytea** [bleakgrey/tootle#44]
`(tootle:9662): Gtk-WARNING **: Failed to set text '<b>V?ctor Gabriel <(&apos;)</b>' from markup due to error parsing markup: Error on line 1 char 39: '(&apos;)<' is not a valid name`

This is the status: https://todon.nl/@hermesgabriel/100151455466573913

**Comment by bleakgrey** [comment]
People absolutely love special characters I have to escape, don't they -_-

**Comment by tastytea** [comment]
I feel you, had to implement all the HTML entites too, a while ago.
Here is a list that might help: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
