### ISSUE TITLE
Some hashtags open in the browser

### ISSUE THREAD

**Issue by tastytea** [bleakgrey/tootle#46]
Version: 0.1.3
Example status: https://soc.freedombone.net/objects/8fd66cff-ed8d-4c24-8a65-691782535379 

It seems that tags from Pleroma and GNUSocial are affected.

**Comment by bleakgrey** [comment]
Yup, Tootle supports Mastodon API only and can't request data from other types of instances. I think opening those links in a browser is better than silently failing.

**Comment by tastytea** [comment]
Tootle could look up the tag-URL in the status and use that instead. The tag-URL points to the instance of the logged-in user. For the example status that would be:

```JSON
{
…
    "tags" : [
      {
         "url" : "https://soc.ialis.me/tags/spycops",
         "name" : "spycops"
      }             
    ],
…
}
```
