### ISSUE TITLE
Resize non-Mastodon image attachments

### ISSUE THREAD

**Issue by lanodan** [bleakgrey/tootle#49]
I don’t know if it’s because pleroma doesn’t do thumbnails (it probably happens on mastodon with a small window anyway).
But scaling down the pictures would be neat, so I don’t have to make the window wider to see it full size or so it doesn’t take up a huge part of the window.

* Version: 0.1.3
* Fullscreen: ![fullscreen](https://user-images.githubusercontent.com/3816428/41190986-957bb08c-6be8-11e8-9597-ca1ae738b96e.png)
* Half-screen: ![half-screen](https://user-images.githubusercontent.com/3816428/41190996-b55fe04e-6be8-11e8-9198-fbe2b444568b.png)

Edit: Added client version

**Comment by bleakgrey** [comment]
It doesn't happen on Masto instances since they provide a small preview version which I use so Tootle don't have to resize them. I'm not sure whether I want to implement this just for Pleroma :/

**Comment by Null-Senpai** [comment]
I second this, it would be really nice if this was implemented somehow. 
I know "me too" posts are not really productive, but I just wanna say that there's a lot of pleroma instances out there, and they seem to be gaining traction. It would be really nice if you could implement this.

PS: Thanks for the client anyhow, even without this feature it's pretty great. A native app (Corebird) was the only reason I was still using twitter~

**Comment by lanodan** [comment]
Well maybe if the author doesn’t want to work on it it would have to be done with a PR.
Sadly I have absolutely no skills with GTK or vala.

Also It would probably also benefit users of High DPI screens on mastodon so they don’t end up with blurry or too small images.

**Comment by bleakgrey** [comment]
I'll see what I can do. Also I'm not quite sure how scaling images even further down on HDPI displays would prevent blurry images :/

**Comment by Null-Senpai** [comment]
Thanks!
Also, I guess technically adding an option to use full-res images even on mastodon, and then just scaling them to fit inside the client would be the best way for High-DPI? Not sure how much work that would be though. Either way, images would need to actually be scaled.

**Comment by bleakgrey** [comment]
The thing is that GTK isn't HTML with full CSS support. I can't make the images go like "oh hey the user is resizing the window, guess I'll just resize myself too to fit in". Instead what it makes is something like "oh so you need to resize me? how about 5 seconds freeze while you're resizing me through CSS or a huge memory clog if you dare enough to do it manually".

I'm working with the second option and I try to refrain from rescaling images where possible. Pleroma's whim about supplying the original URL for a thumbnail doesn't make me happy. But I guess that's what you get when dealing with federated instances.

**Comment by bleakgrey** [comment]
This should about do it. Can anyone test the master branch to see if it's okay now?

**Comment by lanodan** [comment]
Looks like it works now.
Thanks a lot!

**Comment by null-von-sushi** [comment]
Uh, not sure if I misunderstood the issue, but it doesn't seem to work for me?
I cloned the git and compiled it, images are still way too large. 
![a1](https://user-images.githubusercontent.com/13616397/42297715-4d789b72-7ff9-11e8-88ca-dffacf071673.png)

Even if I resize the window beyond my display's size, things still look....off
![a3](https://user-images.githubusercontent.com/13616397/42297727-6103f2fe-7ff9-11e8-89db-83533e1e8c1b.png)

**Comment by lanodan** [comment]
Can’t reproduce here… 
![screen](https://user-images.githubusercontent.com/3816428/42300911-f26049dc-8012-11e8-928a-55b24d738b4d.png)

**Comment by bleakgrey** [comment]
Have you been fiddling with dconf by any chance? Resizing doesn't work properly with cache turned on yet.

**Comment by null-von-sushi** [comment]
I am not sure where you got a 'dependency graph' from. I can just manually type the package names and versions if it helps?

> Have you been fiddling with dconf by any chance? Resizing doesn't work properly with cache turned on yet.

In general yes, since settings are disappearing from GNOME GUIS at a rapid rate. However nothing to do with tootle. I haven't touched it's dconf entry. 
Under settings I see no entry for caching...

**Comment by bleakgrey** [comment]
Honestly I don't think this has something to do with dependencies. The code for resizing is almost pure GTK and GLib. 

Can you try reinstalling Tootle completely? Uninstall it with
```
sudo ninja uninstall
```
and then follow the instructions from README.md

**Comment by null-von-sushi** [comment]
Dunno how or why, but it works now. Weird. Thank you very much for fixing this though.
I just want to mention that while resizing does indeed work now, the last image might get cropped if you have your client ridiculously narrow, but everything works a-ok when it's fullscreen or at a normal width.


![a1](https://user-images.githubusercontent.com/13616397/42358643-8d729d72-80d5-11e8-8f22-b9e551746715.png)
![a2](https://user-images.githubusercontent.com/13616397/42358644-8d8fbe5c-80d5-11e8-83b7-2c1026485b8e.png)
