### ISSUE TITLE
Add "Clear all notifications" button

### ISSUE THREAD

**Issue by BaptisteGelez** [bleakgrey/tootle#5]
It would be nice to have the same behavior as the Wingpanel indicator for notifications: only show a bell when there is no unread notifications, and the bell with a red dot when we have received a new one.

**Comment by bleakgrey** [comment]
It should already do that if you have dismissed all of the notifications :/

**Comment by bleakgrey** [comment]
I just checked that and it works as expected, although it loads old notifications on start and displays them as new.

I'll add a new "Clear all" button or something something to fix that.

**Comment by bleakgrey** [comment]
Dupe of #81
