### ISSUE TITLE
0.1.4 crashes soon after launch

### ISSUE THREAD

**Issue by wezm** [bleakgrey/tootle#55]
Just upgraded to 0.1.4 from 0.1.3 and Tootle is crashing soon after launch with this error:

```
[INFO 20:18:09.919818] Application.vala:154: Tootle version: 0.1.4
[INFO 20:18:09.919841] Application.vala:156: Kernel version: 4.16.13-2-ARCH

(com.github.bleakgrey.tootle:10914): Gtk-WARNING **: 20:18:09.997: gtk_window_set_titlebar() called on a realized window
[ERROR 20:18:14.000888] Notificator.vala:57: Received invalid WebSocket response from the server
[1]    10914 trace trap (core dumped)  com.github.bleakgrey.tootle
```

I'm on Arch Linux, gtk 3.22.30-1, my mastodon instance is mastodon.social, which is running Mastodon 2.4.2 at the time of writing.

**Comment by bleakgrey** [comment]
Well that was quick

**Comment by bleakgrey** [comment]
Can you please build the master version and copy the terminal output here? I can't seem to understand where it fails.

**Comment by wezm** [comment]
> Well that was quick

I maintain [the AUR package](https://aur.archlinux.org/packages/tootle/) and have set up Feedbin to ping me when there's a new release. :)

I deleted `~/.config/com.github.bleakgrey.tootle` to try signing in again. This time it crashed after entering "mastodon.social" in the initial dialog:

```
[INFO 20:38:20.929631] Application.vala:154: Tootle version: 0.1.4
[INFO 20:38:20.929656] Application.vala:156: Kernel version: 4.16.13-2-ARCH
Gtk-Message: 20:38:20.973: GtkDialog mapped without a transient parent. This is discouraged.
[FATAL 20:38:30.121087] [Json] json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed
[FATAL 20:38:30.121144] [Json] json_object_get_string_member: assertion 'object != NULL' failed
[FATAL 20:38:30.121180] [Json] json_object_get_string_member: assertion 'object != NULL' failed
[1]    13721 segmentation fault (core dumped)  com.github.bleakgrey.tootle
```

Additionally the web page opened showed:

> Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method. 

On `master`: 

> Can you please build the master version and copy the terminal output here? I can't seem to understand where it fails.

```
[INFO 20:53:51.542632] Application.vala:154: Tootle version: 0.1.4
[INFO 20:53:51.542663] Application.vala:156: Kernel version: 4.16.13-2-ARCH
(com.github.bleakgrey.tootle:15188): Gtk-DEBUG: 20:53:51.545: Connecting to session manager
Gtk-Message: 20:53:51.697: GtkDialog mapped without a transient parent. This is discouraged.
[FATAL 20:53:59.345201] [Json] json_node_get_object: assertion 'JSON_NODE_IS_VALID (node)' failed
[FATAL 20:53:59.345265] [Json] json_object_get_string_member: assertion 'object != NULL' failed
[FATAL 20:53:59.345301] [Json] json_object_get_string_member: assertion 'object != NULL' failed
[INFO 20:53:59.345333] NewAccountDialog.vala:136: Received tokens from https://mastodon.social
[INFO 20:53:59.345365] NewAccountDialog.vala:149: Requesting auth token
```

Any tips on how to debug Vala programs? I can run it gdb and set breakpoints etc. but can't seem to examine any locals.

**Comment by bleakgrey** [comment]
Oh cool, they must've changed the way the apps are authorized too. Nice minor update...

I'm gonna tinker with this a bit. I'll keep you posted.

**Comment by bleakgrey** [comment]
Haha no, it's actually my fault. I accidently broke custom behavior for non-user network requests.

**Comment by bleakgrey** [comment]
Alright, I fixed the new account dialog. But I have no idea why notificators crash almost immediately after adding a new account. It's not Masto's new version fault as 0.1.3 runs without this issue.

I've spent 2 hours trying to understand what happens but honestly I have no idea what's going on. All I get in the terminal is `[libsoup] soup_websocket_connection_new: assertion 'G_IS_IO_STREAM (stream)' failed` :c 

Restarting Tootle magically fixes this bug until a new account is added.

**Comment by wezm** [comment]
I did a git bisect and 8ef015be91a03c5a1e62d7c52c045b613b174349 is the commit at which it starts crashing for me.

**Comment by bleakgrey** [comment]
I'm actually glad this issue popped up right now as it uncovered some potential problems with notificators. Can you check if the master works for you now?

**Comment by wezm** [comment]
No crashes on current master after a few minutes of use :+1:

**Comment by bleakgrey** [comment]
Cool, thanks for your feedback :)
