### ISSUE TITLE
Can't find the key 'char-limit'

### ISSUE THREAD

**Issue by tastytea** [bleakgrey/tootle#57]
Since 0.14.0 (and as of commit 84985485847a3570dd1292ce33dfd272f2e4ab31) tootle crashes right at the beginning. This is the output:
```
[INFO 16:52:57.957917] Application.vala:154: Tootle version: 0.1.4
[INFO 16:52:57.958016] Application.vala:156: Kernel version: 4.14.50-gentoo
[ERROR 16:52:58.020034] [GLib-GIO] Settings schema 'com.github.bleakgrey.tootle' does not contain a key named 'char-limit'
```
But `/usr/share/glib-2.0/schemas/com.github.bleakgrey.tootle.gschema.xml` has a key named `char-limit`: [com.github.bleakgrey.tootle.gschema.xml](https://github.com/bleakgrey/tootle/files/2119855/com.github.bleakgrey.tootle.gschema.xml.txt)

I used the exact same procedure to install 0.1.4 as i did with 0.1.3, which ran fine. I ran `sudo glib-compile-schemas /usr/share/glib-2.0/schemas` but it didn't help.

**Comment by bleakgrey** [comment]
Sometimes this happens with meson. All you have to do is completely uninstall Tootle with `sudo ninja uninstall` and then install it again with `sudo ninja install`. Please refer to README.md for installation info.

**Comment by tastytea** [comment]
That didn't help. I uninstalled the package I created for Gentoo first, then cloned the repo, installed it as shown in README.md.
To be absolutely sure i uninstalled it again with `sudo ninja uninstall` and installed it again with `sudo ninja install`. `/usr/share/glib-2.0/schemas/gschemas.compiled` was updated in the process, the timestamp changed.

**Comment by bleakgrey** [comment]
That's weird... the schema should've regenerated at least once. Can you check if domain `com.github.bleakgrey.tootle` has a key `char-limit` in dconf?

**Comment by bleakgrey** [comment]
Also please make sure that this is the exact same issue as 0.1.4 has a potential crash at startup right now

**Comment by tastytea** [comment]
`dconf dump /com/github/bleakgrey/tootle/` showed:
```
[/]
dark-theme=true
always-online=true
```
The error message is the same as above.

**Comment by bleakgrey** [comment]
That's a suspiciously short list. Does meson print any schema warnings during building/installation? Could be something like "the entire file has been ignored".

**Comment by bleakgrey** [comment]
It also feels like there could be an outdated schema file somewhere in your system that overrides the new one. Did you use the same building prefix as the last time you compiled Tootle?

**Comment by tastytea** [comment]
I found the file `/usr/local/share/glib-2.0/schemas/gschemas.compiled`. It seems i had installed tootle once with --prefix=/usr/local and the deinstallation didn't remove the compiled file. m( It works now, thanks.

**Comment by bleakgrey** [comment]
You're always welcome :)

**Comment by robertsanseries** [comment]
@tastytea Thanks for the answer! this helped me a lot in another application!
