### ISSUE TITLE
"Copy link" and "Open in browser" do not work on boosts

### ISSUE THREAD

**Issue by martensitingale** [bleakgrey/tootle#62]
They cause, respectively, the following error messages to be printed instead:
```
tootle_desktop_copy: assertion 'str != NULL' failed
```
```
tootle_desktop_open_uri: assertion 'uri != NULL' failed
```

**Comment by bleakgrey** [comment]
The official API made the "url" field nullable for some reason :/
I'll add a fallback to the "uri" param in the status handling.
