### ISSUE TITLE
Reply to user where toot has its own username doubles mentions

### ISSUE THREAD

**Issue by mrvdb** [bleakgrey/tootle#63]
Example:
 
![20180711_1856](https://user-images.githubusercontent.com/73067/42587891-64661cfe-853c-11e8-9b43-4e781aa189c7.png)

**Comment by bleakgrey** [comment]
I can't find similar toots to test the fix. Can you please check if the master branch works correctly now?

**Comment by mrvdb** [comment]
Yep, works fine, thanks!
