### ISSUE TITLE
SOCKS proxy

### ISSUE THREAD

**Issue by Oreolek** [bleakgrey/tootle#66]
My Mastodon instance is erroneously blocked (451) in Russia because of an IP block. Can you add a proxy option?

**Comment by bleakgrey** [comment]
Yeah, I think libsoup supports that

**Comment by alcinnz** [comment]
I think this is the appropriate property to use here: https://valadoc.org/libsoup-2.4/Soup.Session.proxy_uri.html .

**Comment by bleakgrey** [comment]
Seeing that Soup's `proxy_uri` has got deprecated, I'm going to close this. Many DEs support system-wide proxies out of the box anyway.

Here's GNOME Settings, for example.
![Screenshot from 2020-06-01 04-03-01](https://user-images.githubusercontent.com/20158357/83367397-fc485780-a3bc-11ea-8576-af9414683f60.png)
