### ISSUE TITLE
Flatpak-ing tootle!

### ISSUE THREAD

**Issue by BharatKalluri** [bleakgrey/tootle#67]
Hey!

Thanks for your work! I made a flatpak version of tootle. It is up [here](https://github.com/BharatKalluri/tootle-flatpak.git). If you have any queries, feel free to ping me in this thread.

Test this out, and lets iron out the rough edges and push it to flathub.

Cheers!

**Comment by pianycist** [comment]
There is also this one: https://gitlab.com/cagatay-y/tootle-flatpak/

Flatpaks are excellent!

**Comment by koyuawsmbrtn** [comment]
This would be awesome. I'm a big fan of GNOME and their technologies like Flatpaks.

**Comment by bilelmoussaoui** [comment]
Pushed the app to Flathub using elementary Loki's baseApp. https://github.com/flathub/flathub/pull/518

**Comment by bleakgrey** [comment]
Woah, that's a lot of people who'd like Tootle in Flatpak form :D 
Thank you all for your efforts, I'll see if I can publish the next major version with official Flatpak support

**Comment by bilelmoussaoui** [comment]
Can be closed. In less an hour, the app was packaged, published on Flathub and can be installed. Will soon be shown on the flathub store.
