### ISSUE TITLE
Ctrl+enter to send toots

### ISSUE THREAD

**Issue by drequivalent** [bleakgrey/tootle#78]
Subj.

It's a conventional shortcut for sending stuff both in IMs and in Mastodon web interface, and even here on Github it works.

**Comment by cagatay-y** [comment]
There is a similar request at https://github.com/bleakgrey/tootle/issues/12#issuecomment-391817461.

**Comment by drequivalent** [comment]
Oh well.

Okay then.

**Comment by caetano-m** [comment]
I am a bit confused, both this request and  [#12 (comment)](https://github.com/bleakgrey/tootle/issues/12#issuecomment-391817461) are closed. Yet, there is no ctrl+enter shortcut for sending new tootles.
