### ISSUE TITLE
View media inside the app

### ISSUE THREAD

**Issue by drequivalent** [bleakgrey/tootle#79]
It's better not to open browser on every picture you want to take a closer look at. Too much movement, it's startling, and also there may be a tab open in my browser I don't want to click away from.

It's better avoid redirecting the user to browser whenever possible overall.

**Comment by bleakgrey** [comment]
Clicking on an attachment now opens it in the default associated application. I'll consider adding separate views for photos, videos and audio attachments in the future.

Still better than opening a browser.
