### ISSUE TITLE
Allow pinning hashtags 

### ISSUE THREAD

**Issue by alcinnz** [bleakgrey/tootle#8]
While I don't personally use hashtags that much, I am following #100daysofcode. As such it'd be useful if open locating a hashtag like that one I could click a button to add a tab to it into the headerbar, or something to that effect. Basically I just want quick access to arbitrary hashtags I've previously selected.

**Comment by bleakgrey** [comment]
I don't like the idea of adding another tab to the header. The app was designed to be visually simple and neat and I feel like five tab would be too many.

I had an idea the other day about adding something like a "Stash" - a popup with frequent answers that opens through a key shortcut or something. Maybe we could connect hashtags and text snippets into a one thing somehow?

**Comment by bleakgrey** [comment]
I've pondered about this a little and decided that this will be partially implemented in #33. I'm not sure if I want to make a panel with "pinned" hashtags as I don't want to overcomplicate the UI, so I'll just make the "watching" part for now.
