### ISSUE TITLE
Fit images inside the window

### ISSUE THREAD

**Issue by drequivalent** [bleakgrey/tootle#80]
Horizontal scrollbars on vertically-scrolling timelines are baffling. Sometimes the picture is too big to fit into the window. Sometimes you only see one picture in the toot, while it has more of them - and you don't even notice the scrollbar. And you also have to find the scrollbar, aim at it and scroll it. Only then you see the rest of the pictures. That is the problem, especially when you are subscribed to the art community, the client quickly becomes less than usable.

I think the scrollbar must go. I think, if the image is too big, fit it. If there's more than one, tile them.

**Comment by lanodan** [comment]
Or it should at least be changed to a vertical scrollbar, just keep enough margins to be able to avoid it if wanted.

**Comment by bleakgrey** [comment]
Wish granted! 3305fac
