### ISSUE TITLE
The client doesn't reset the notification button/Add "Mark everything as read" to the notifications

### ISSUE THREAD

**Issue by drequivalent** [bleakgrey/tootle#81]
My Tootle always thinks that there's new notifications. It somehow always shoes the red dot on the Bell button. I think, it should reset as soon as the user presses it and the window is active.

If the window is inactive, but I'm on the Notifications tab, the dot should disappear as soon as the users activate the window.

Also, there should be an option of switching the red dot off if the user has a backlog of notifications that they don't want to deal with, or they have read them on the other device.

**Comment by bleakgrey** [comment]
Wish granted~ :sparkles:
