### ISSUE TITLE
Font size or zoom

### ISSUE THREAD

**Issue by jeroenpraat** [bleakgrey/tootle#86]
Please add an option to increase (and decrease) the font size or add zooming.

**Comment by fschaap** [comment]
It would be nice if font size could be a preferences setting.

In the meantime it's possible to launch Tootle with an environment variable to enlarge the text. A bit hacky, but it works. At least, it works for me: Cinnamon DE on Manjaro. I guess this works for Gnome/GTK DEs, don't know about KDE/Qt.

`env GDK_SCALE=1.3 GDK_DPI_SCALE=1.3 CLUTTER_SCALE=1.3 /usr/bin/corebird`

**Comment by keponk** [comment]
+1 on this! Loving this clean, fast and simple app. Great work!

I'm getting old though and would be nice to increase the font size :)
