### ISSUE TITLE
Opening and closing a CW'd toot quickly instead opens the toot in detail view

### ISSUE THREAD

**Issue by LeoTindall** [bleakgrey/tootle#90]
If you, e.g., double click a "Toggle content" button, the toot is opened in detail view rather than toggling the visibility of the content twice.

**Comment by bleakgrey** [comment]
I can't pinpoint where this is coming from. This may be a result of layout size updating during the animation, but I'm not sure what I can do here.

This is not a critical UX bug, so I'll close it for now.
