### ISSUE TITLE
Cannot generate code from flatpak installation

### ISSUE THREAD

**Issue by kwill** [bleakgrey/tootle#93]
I've installed Tootle from Flathub. On launch it prompts for an instance domain, then a code. I know my instance domain, but what "code" should I be providing? The tooltip just says "Paste your authorization code here".

**Steps to reproduce:**

* `flatpak run com.github.bleakgrey.tootle`
* Next to "Instance" enter "mastodon.social"

**What should happen:**

* Opens tab in browser
* (Proceed to enter code next to "Code")

**What happens instead:**

* Nothing. Command line traceback:

```
Gtk-Message: 12:22:08.078: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:22:08.078: Failed to load module "canberra-gtk-module"
[INFO 12:22:08.078558] Application.vala:155: Tootle version: 0.1.5
[INFO 12:22:08.078580] Application.vala:157: Kernel version: 4.18.0-1-amd64
Gtk-Message: 12:22:08.131: GtkDialog mapped without a transient parent. This is discouraged.
[FATAL 12:22:11.170458] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FATAL 12:22:17.222899] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[INFO 12:22:19.235060] NewAccountDialog.vala:136: Received tokens from https://mastodon.social
[INFO 12:22:19.235166] NewAccountDialog.vala:150: Requesting auth token
```

**Comment by BaptisteGelez** [comment]
It should normally open a new tab in your web browser with the code to copy/paste, but I guess it is not working because of containerization…

**Comment by cagatay-y** [comment]
Do you get an error message or something? There is a bug (#74) that causes a "Cannot resolve hostname" error when a instance URL starting with `https://` is entered. There is a work around for it (https://github.com/bleakgrey/tootle/issues/74#issuecomment-423594945).

**Comment by kwill** [comment]
The following attempt works:

* `gio open https://mastodon.social/oauth/authorize`

...but the full URL fails:

* `gio open "https://mastodon.social/oauth/authorize/?scope=read%20write%20follow&response_type=code&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client_id=x"`

...with an error in custom script on my side. I will look into this and see if I can reproduce on my side without the customisation.

**Comment by kwill** [comment]
This was an error in my custom script, unrelated to Tootle.
