### ISSUE TITLE
wierdness i can't easly explain

### ISSUE THREAD

**Issue by unmellow** [bleakgrey/tootle#94]
![herm](https://user-images.githubusercontent.com/30985587/45843941-ec730780-bcee-11e8-9eef-a1779a3cc11e.jpg)

when I click to show the thread for a post I original post goes white like that and then I can't read it I'm using manjaro with lxqt

**Comment by bleakgrey** [comment]
Did you try turning on dark mode in the settings?

**Comment by unmellow** [comment]
thanks i didn't know that was an option
