### ISSUE TITLE
Releasing for Juno

### ISSUE THREAD

**Issue by koyuawsmbrtn** [bleakgrey/tootle#96]
I tested the app for Juno and infrastructure-wise and design-wise it looks pretty good.

![Screenshot of Tootle in Juno](https://user-images.githubusercontent.com/40538332/45916628-94144500-be69-11e8-896e-5f103ec56cb0.png)

So can we release it now?

**Comment by danrabbit** [comment]
Our [second Juno Developer Preview](https://medium.com/elementaryos/developer-preview-juno-beta-2-is-out-418f5037e9bb) is out and Juno's big debut is just around the corner! We'd love to see your app in AppCenter on release day.

Check out this [Developer Tips](https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7) article to learn how to publish your app for elementary OS 5.

If you need help updating your app for Juno, we’re always standing by in [Gitter](https://gitter.im/elementary/houston) and the [Community Slack](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc) to help wherever we can.

**Comment by koyuawsmbrtn** [comment]
I just talked to @bleakgrey and he will be doing it soon :)

**Comment by beli3ver** [comment]
Is there a date?

**Comment by koyuawsmbrtn** [comment]
@beli3ver not that i know of

**Comment by koyuawsmbrtn** [comment]
Version bump! (`28551b77b77edbacf33506652cebdff13163e611`)
