### ISSUE TITLE
Remember window state/size

### ISSUE THREAD

**Issue by aldomann** [bleakgrey/tootle#99]
As the title says, it would be nice to remember the window state when closed. 

I prefer the window to be a bit wider than the default, but after closing the application, the window size is back to the original size. I checked on dconf Editor and there's no key to change the window state.

**Comment by bleakgrey** [comment]
Wish granted!

**Comment by pztrn** [comment]
Hey, could you please make a new release with this change?

**Comment by bleakgrey** [comment]
There's still lots of code I need to rewrite, so I can't publish a new release in its current state.

You still can compile master branch, though.
